version: "3.7"
services:

  app:
    build:
      args:
        user: www
        uid: 1000
      context: ./.docker/php
      dockerfile: Dockerfile
    container_name: "${APP_NAME}"
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www:delegated
      - /var/www/.git
    networks:
      - hyperoptic

  nginx:
    image: nginx:alpine
    container_name: nginx-webserver
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/public:delegated
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - hyperoptic

networks:
  hyperoptic:
    driver: bridge
